apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: restorejobs.k8sbackup.dev
spec:
  scope: Namespaced
  group: k8sbackup.dev
  names:
    kind: RestoreJob
    plural: restorejobs
    singular: restorejob
    shortNames:
      - rj
    categories:
      - k8sbackup

  versions:
    - name: v1
      served: true
      storage: true

      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gitRef:
                  type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                  x-kubernetes-preserve-unknown-fields: true
                ready:
                  type: boolean
                kopf:
                  type: object
              x-kubernetes-preserve-unknown-fields: true
      subresources:
        status: {}

      additionalPrinterColumns:
        - name: Git Ref
          type: string
          description: Git Reference to be restored
          jsonPath: .spec.gitRef